// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: tag.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TagR struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text *Trs   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *TagR) Reset() {
	*x = TagR{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagR) ProtoMessage() {}

func (x *TagR) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagR.ProtoReflect.Descriptor instead.
func (*TagR) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{0}
}

func (x *TagR) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagR) GetText() *Trs {
	if x != nil {
		return x.Text
	}
	return nil
}

type TagUpdateI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auth *AuthI `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Text *Trs   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *TagUpdateI) Reset() {
	*x = TagUpdateI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagUpdateI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagUpdateI) ProtoMessage() {}

func (x *TagUpdateI) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagUpdateI.ProtoReflect.Descriptor instead.
func (*TagUpdateI) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{1}
}

func (x *TagUpdateI) GetAuth() *AuthI {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *TagUpdateI) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagUpdateI) GetText() *Trs {
	if x != nil {
		return x.Text
	}
	return nil
}

type TagCreateI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auth *AuthI `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Text *Trs   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *TagCreateI) Reset() {
	*x = TagCreateI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagCreateI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagCreateI) ProtoMessage() {}

func (x *TagCreateI) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagCreateI.ProtoReflect.Descriptor instead.
func (*TagCreateI) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{2}
}

func (x *TagCreateI) GetAuth() *AuthI {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *TagCreateI) GetText() *Trs {
	if x != nil {
		return x.Text
	}
	return nil
}

type TagListR struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*TagR `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *TagListR) Reset() {
	*x = TagListR{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tag_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagListR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagListR) ProtoMessage() {}

func (x *TagListR) ProtoReflect() protoreflect.Message {
	mi := &file_tag_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagListR.ProtoReflect.Descriptor instead.
func (*TagListR) Descriptor() ([]byte, []int) {
	return file_tag_proto_rawDescGZIP(), []int{3}
}

func (x *TagListR) GetItems() []*TagR {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_tag_proto protoreflect.FileDescriptor

var file_tag_proto_rawDesc = []byte{
	0x0a, 0x09, 0x74, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69,
	0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34,
	0x0a, 0x04, 0x54, 0x61, 0x67, 0x52, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x72, 0x73, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x22, 0x5a, 0x0a, 0x0a, 0x54, 0x61, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x49, 0x12, 0x1e, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x49, 0x52, 0x04, 0x61, 0x75,
	0x74, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1c, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x72, 0x73, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x22, 0x4a, 0x0a, 0x0a, 0x54, 0x61, 0x67, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x12, 0x1e,
	0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x49, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x1c,
	0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x54, 0x72, 0x73, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x2b, 0x0a, 0x08,
	0x54, 0x61, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x12, 0x1f, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61,
	0x67, 0x52, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x32, 0xf2, 0x01, 0x0a, 0x04, 0x54, 0x61,
	0x67, 0x53, 0x12, 0x26, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x0f, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x54, 0x61, 0x67, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x1a, 0x09, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x22, 0x00, 0x12, 0x26, 0x0a, 0x06, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x67, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x49, 0x1a, 0x09, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x67, 0x52,
	0x22, 0x00, 0x12, 0x24, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x0d, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x49, 0x1a, 0x09, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x22, 0x00, 0x12, 0x20, 0x0a, 0x02, 0x49, 0x64, 0x12, 0x0d,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x49, 0x1a, 0x09, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x22, 0x00, 0x12, 0x27, 0x0a, 0x06, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x12, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x49, 0x1a, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x67, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x0d,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x49, 0x1a, 0x0d, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x22, 0x00, 0x42, 0x0a,
	0x5a, 0x08, 0x2e, 0x2f, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_tag_proto_rawDescOnce sync.Once
	file_tag_proto_rawDescData = file_tag_proto_rawDesc
)

func file_tag_proto_rawDescGZIP() []byte {
	file_tag_proto_rawDescOnce.Do(func() {
		file_tag_proto_rawDescData = protoimpl.X.CompressGZIP(file_tag_proto_rawDescData)
	})
	return file_tag_proto_rawDescData
}

var file_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tag_proto_goTypes = []interface{}{
	(*TagR)(nil),       // 0: api.TagR
	(*TagUpdateI)(nil), // 1: api.TagUpdateI
	(*TagCreateI)(nil), // 2: api.TagCreateI
	(*TagListR)(nil),   // 3: api.TagListR
	(*Trs)(nil),        // 4: api.Trs
	(*AuthI)(nil),      // 5: api.AuthI
	(*GetByIdI)(nil),   // 6: api.GetByIdI
	(*SearchI)(nil),    // 7: api.SearchI
}
var file_tag_proto_depIdxs = []int32{
	4,  // 0: api.TagR.text:type_name -> api.Trs
	5,  // 1: api.TagUpdateI.auth:type_name -> api.AuthI
	4,  // 2: api.TagUpdateI.text:type_name -> api.Trs
	5,  // 3: api.TagCreateI.auth:type_name -> api.AuthI
	4,  // 4: api.TagCreateI.text:type_name -> api.Trs
	0,  // 5: api.TagListR.items:type_name -> api.TagR
	2,  // 6: api.TagS.Create:input_type -> api.TagCreateI
	1,  // 7: api.TagS.Update:input_type -> api.TagUpdateI
	6,  // 8: api.TagS.Delete:input_type -> api.GetByIdI
	6,  // 9: api.TagS.Id:input_type -> api.GetByIdI
	7,  // 10: api.TagS.Search:input_type -> api.SearchI
	6,  // 11: api.TagS.Service:input_type -> api.GetByIdI
	0,  // 12: api.TagS.Create:output_type -> api.TagR
	0,  // 13: api.TagS.Update:output_type -> api.TagR
	0,  // 14: api.TagS.Delete:output_type -> api.TagR
	0,  // 15: api.TagS.Id:output_type -> api.TagR
	3,  // 16: api.TagS.Search:output_type -> api.TagListR
	3,  // 17: api.TagS.Service:output_type -> api.TagListR
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_tag_proto_init() }
func file_tag_proto_init() {
	if File_tag_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_tag_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagR); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagUpdateI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagCreateI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tag_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagListR); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tag_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tag_proto_goTypes,
		DependencyIndexes: file_tag_proto_depIdxs,
		MessageInfos:      file_tag_proto_msgTypes,
	}.Build()
	File_tag_proto = out.File
	file_tag_proto_rawDesc = nil
	file_tag_proto_goTypes = nil
	file_tag_proto_depIdxs = nil
}
